# Generated by Django 2.1.3 on 2018-12-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionOne', models.CharField(max_length=3)),
                ('questionTwo', models.CharField(max_length=17)),
                ('questionThree', models.CharField(max_length=17)),
                ('questionFour', models.CharField(max_length=17)),
                ('questionFive', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
